version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beai-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public